### ISSUE TITLE
It simply doesn't work !

### ISSUE THREAD

**Issue by nicolasduminil** [hyteio/activemq-client-jakarta#6]
The ActiveMQConnectionFactory.createConnection(...) in org.apache.activemq:activemq-client:5.18.0-SNAPSHOT still returns javax.jms.Connection. I wasted my time trying to get it working. I should have known better that if you avoided to provide any source code, it was for a reason.

**Comment by mattrpav** [comment]
@nicolasduminil let me take a look. The reason there is no source code, is that this module takes the activemq-client source as-is and renames the javax.jms package to jakarta.jms. There should be no need for any source changes.

see pom.xml:

```
<configuration>
  <includes>
    <include>${project.build.directory}/copied-sources/activemq-client/**/*.java</include>
  </includes>
  <token>javax.jms</token>
  <value>jakarta.jms</value>
  <regexFlags>
    <regexFlag>MULTILINE</regexFlag>
  </regexFlags>
</configuration>
```

**Comment by mattrpav** [comment]
@nicolasduminil I think your Maven dependency needs to be adjusted to use this transition client.

```
<dependency>
  <groupId>io.hyte.activemq</groupId>
  <artifactId>activemq-client-jakarta</artifactId>
  <version>5.18.0.hyte-1</version>
</dependency>
```

| Provider | GroupId | ArtifactId | Note |
| --- | --- | --- | --- |
| Apache | org.apache.activemq | activmeq-client | The client from Apache 5.18.0 is javax.jms with JMS 2.0 preview support |
| HYTE | io.hyte.activemq | activemq-client-jakarta | The client from HYTE is repackaged for jakarta.jms with JMS 2.0 preview support |

At Apache ActiveMQ, we are working towards an apache release client with jakarta support that will come in 5.18.x or 5.19.x.

**Comment by mattrpav** [comment]
see this test class confirming jakarta namespace is correct:

https://github.com/hyteio/activemq-client-jakarta/blob/main/src/test/java/org/apache/activemq/jakarta/JakartaTest.java
